services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - certbot
    networks:
      - food-keeper

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  spring:
    image: seoarc/food-keeper-server:latest
    container_name: food-keeper-api-server
    restart: on-failure:3
    environment:
      SPRING_PROFILES_ACTIVE: dev
      TZ: Asia/Seoul
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      NAVER_STORAGE_ACCESS_KEY: ${NAVER_STORAGE_ACCESS_KEY}
      NAVER_STORAGE_SECRET_KEY: ${NAVER_STORAGE_SECRET_KEY}
      NAVER_STORAGE_URL: ${NAVER_STORAGE_URL}
      CLOVA_MODEL_URL: ${CLOVA_MODEL_URL}
      CLOVA_API_KEY: ${CLOVA_API_KEY}
      CLIENT_URL: ${CLIENT_URL}
    ports:
      - "8080:8080"
    networks:
      - food-keeper
    volumes:
      - ./:/app/local
      - ./logs:/var/log/spring

  mysql:
    image: mysql:8.0.44-debian
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    command: [
       "--character-set-server=utf8mb4",
       "--collation-server=utf8mb4_unicode_ci"
    ]
    networks:
      - food-keeper
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.dev.yml:/etc/promtail/config.yml
      - /var/log/food-keeper:/var/log/app
      - /var/lib/promtail:/var/lib/promtail
    command: -config.file=/etc/promtail/config.yml
    networks:
      - food-keeper

networks:
  food-keeper:
    driver: bridge