services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - certbot
    networks:
      - kitchen-log

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c 'trap exit TERM; while :; do certbot renew --deploy-hook "nginx -s reload"; sleep 12h & wait $${!}; done;'
    networks:
      - kitchen-log

  spring_blue:
    image: seoarc/kitchen-log-server:latest
    container_name: spring_blue
    restart: on-failure:3
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
      AWS_ACCESS_KEY_ID: ${DB_URL}
      AWS_SECRET_ACCESS_KEY: ${DB_USERNAME}
      AWS_REGION: ${DB_PASSWORD}
    networks:
      - kitchen-log
    volumes:
      - ./:/app/local
      - /var/log/kitchen-log:/var/log/kitchen-log

  spring_green:
    image: seoarc/kitchen-log-server:latest
    container_name: spring_green
    restart: on-failure:3
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
    networks:
      - kitchen-log
    volumes:
      - ./:/app/local
      - ./logs:/var/log/spring

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.prod.yml:/etc/promtail/config.yml
      - /var/log/kitchen-log:/var/log/app
      - /var/lib/promtail:/var/lib/promtail
    command: -config.file=/etc/promtail/config.yml
    networks:
      - kitchen-log

networks:
  kitchen-log:
    driver: bridge
