services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - certbot
    networks:
      - food-keeper
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c 'trap exit TERM; while :; do certbot renew --deploy-hook "nginx -s reload"; sleep 12h & wait $${!}; done;'
    networks:
      - food-keeper
  spring_blue:
    image: seoarc/food-keeper-server:latest
    container_name: food-keeper-api-blue
    restart: on-failure:3
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - food-keeper
    volumes:
      - ./:/app/local
      - ./logs:/var/log/spring
  spring_green:
    image: seoarc/food-keeper-server:latest
    container_name: food-keeper-api-green
    restart: on-failure:3
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - food-keeper
    volumes:
      - ./:/app/local
      - ./logs:/var/log/spring

networks:
  food-keeper:
    driver: bridge
