services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - certbot
    networks:
      - food-keeper

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c 'trap exit TERM; while :; do certbot renew --deploy-hook "nginx -s reload"; sleep 12h & wait $${!}; done;'
    networks:
      - food-keeper

  spring_blue:
    image: seoarc/food-keeper-server:latest
    container_name: food-keeper-api-blue
    restart: on-failure:3
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      NAVER_STORAGE_ACCESS_KEY: ${NAVER_STORAGE_ACCESS_KEY}
      NAVER_STORAGE_SECRET_KEY: ${NAVER_STORAGE_SECRET_KEY}
      NAVER_STORAGE_URL: ${NAVER_STORAGE_URL}
      CLOVA_MODEL_URL: ${CLOVA_MODEL_URL}
      CLOVA_API_KEY: ${CLOVA_API_KEY}
      CLIENT_URL: ${CLIENT_URL}
      FIREBASE_KEY: ${FIREBASE_KEY}
    networks:
      - food-keeper
    volumes:
      - ./:/app/local
      - /var/log/food-keeper:/var/log/food-keeper

  spring_green:
    image: seoarc/food-keeper-server:latest
    container_name: food-keeper-api-green
    restart: on-failure:3
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      NAVER_STORAGE_ACCESS_KEY: ${NAVER_STORAGE_ACCESS_KEY}
      NAVER_STORAGE_SECRET_KEY: ${NAVER_STORAGE_SECRET_KEY}
      NAVER_STORAGE_URL: ${NAVER_STORAGE_URL}
      CLOVA_MODEL_URL: ${CLOVA_MODEL_URL}
      CLOVA_API_KEY: ${CLOVA_API_KEY}
      CLOVA_GATEWAY_KEY: ${CLOVA_GATEWAY_KEY}
      CLIENT_URL: ${CLIENT_URL}
      FIREBASE_KEY: ${FIREBASE_KEY}
    networks:
      - food-keeper
    volumes:
      - ./:/app/local
      - ./logs:/var/log/spring

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.prod.yml:/etc/promtail/config.yml
      - /var/log/food-keeper:/var/log/app
      - /var/lib/promtail:/var/lib/promtail
    command: -config.file=/etc/promtail/config.yml
    networks:
      - food-keeper

networks:
  food-keeper:
    driver: bridge
