server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://10.0.4.7:3100/loki/api/v1/push

scrape_configs:
  - job_name: food-keeper-prod-log
    static_configs:
      - targets:
          - food-keeper-prod
        labels:
          job: food-keeper-app
          host: food-keeper-prod
          env: dev
          __path__: /var/log/app/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<date>\d{4}-\d{2}-\d{2}) (?P<time>\d{2}:\d{2}:\d{2}\.\d{3}) \[(?P<thread>[^\]]+)\] \[(?P<level>[A-Z]+)\s*\] TraceID\[(?P<trace_id>[^\]]+)\] (?P<logger>[^ ]+) - (?P<msg>.*)$'
      - labels:
          thread:
          level:
          logger:
      - output:
          source: msg
