server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://10.0.20.4:3100/loki/api/v1/push

scrape_configs:
  - job_name: kitchen-log-prod-log
    static_configs:
      - targets:
          - kitchen-log-prod
        labels:
          job: kitchen-log-app
          host: kitchen-log-prod
          env: prod
          __path__: /var/log/app/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<log_time>(?P<date>\d{4}-\d{2}-\d{2}) (?P<time>\d{2}:\d{2}:\d{2}\.\d{3})) \[(?P<thread>[^\]]+)\] \[(?P<level>[A-Z]+)\s*\] TraceID\[(?P<trace_id>[^\]]+)\] (?P<logger>[^ ]+) - (?P<msg>.*)$'

      - timestamp:
          source: date
          format: '2006-01-02 15:04:05.000'
          location: 'Asia/Seoul'

      - labels:
          thread:
          level:
          logger:
          trace_id:

      - template:
          source: output_log
          template: '[{{ .thread }}] TraceID[{{ .trace_id }}] {{ .logger }} - {{ .msg }}'

      - output:
          source: output_log