spring:
  config:
    activate:
      on-profile: dev

  datasource:
    first:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

logging:
  level:
    root: debug
  config: classpath:logback-dev.xml

jwt:
  secret-key: ${JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: food-keeper
    credentials:
      access-key: ${NAVER_STORAGE_ACCESS_KEY}
      secret-key: ${NAVER_STORAGE_SECRET_KEY}
    region:
      static: kr-standard
    stack:
      auto: false

custom:
  s3:
    endpoint: ${NAVER_STORAGE_URL}

clova:
  url: ${CLOVA_MODEL_URL}
  api-key: ${CLOVA_API_KEY}
  gateway-key: ${CLOVA_GATEWAY_KEY}
