spring:
  config:
    activate:
      on-profile: dev


  datasource:
    first:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: validate

springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /v3/api-docs
    disable-swagger-default-url: true
  api-docs:
    enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    root: debug
  config: classpath:logback-dev.xml

jwt:
  secret-key: ${JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${CLOUD_ACCESS_KEY}
      secret-key: ${CLOUD_SECRET_KEY}
    region:
      static: ${CLOUD_REGION}
    stack:
      auto: false

custom:
  s3:
    endpoint: ${NAVER_STORAGE_URL}


clova:
  url: ${CLOVA_MODEL_URL}
  api-key: ${CLOVA_API_KEY}

client:
  url: ${CLIENT_URL}

firebase:
  key: ${FIREBASE_KEY}