spring:
  config:
    activate:
      on-profile: dev
    import: aws-secretsmanager:dev/kitchenlog

  jmx:
    enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  datasource:
    first:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: validate

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /v3/api-docs
    disable-swagger-default-url: true
  api-docs:
    enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
    jmx:
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  jmx:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: debug
  config: classpath:logback-dev.xml

jwt:
  secret-key: ${JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${CLOUD_ACCESS_KEY}
      secret-key: ${CLOUD_SECRET_KEY}
    region:
      static: ${CLOUD_REGION}
    stack:
      auto: false

custom:
  s3:
    endpoint: ${NAVER_STORAGE_URL}


clova:
  url: ${CLOVA_MODEL_URL}
  api-key: ${CLOVA_API_KEY}

client:
  url: ${CLIENT_URL}

firebase:
  key: ${FIREBASE_KEY}

rate-limiter:
  capacity: ${RATE_LIMITER_CAPACITY}
  refill-token-amount: ${RATE_LIMITER_REFILL_TOKEN_AMOUNT}
  refill-duration-seconds: ${RATE_LIMITER_REFILL_DURATION_SECONDS}
  cache-max-size: ${RATE_LIMITER_CACHE_MAX_SIZE}
