spring:
  config:
    activate:
      on-profile: local
    import: "optional:file:.env[.properties]"

  datasource:
    first:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
      username: sa
      password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  level:
    com.foodkeeper: debug

cloud:
  aws:
    s3:
      bucket: food-keeper
    credentials:
      access-key: access-key
      secret-key: secret-key
    region:
      static: kr-standard
    stack:
      auto: false

custom:
  s3:
    endpoint: storage-url

clova:
  url: ${CLOVA_MODEL_URL}
  api-key: ${CLOVA_API_KEY}
