spring:
  config:
    activate:
      on-profile: local

  datasource:
    first:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
      username: sa
      password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  level:
    com.foodkeeper: debug

jwt:
  secret-key: testtesttesttesttesttesttesttest

cloud:
  aws:
    s3:
      bucket: food-keeper
    credentials:
      access-key: access-key
      secret-key: secret-key
    region:
      static: kr-standard
    stack:
      auto: false

custom:
  s3:
    endpoint: storage-url

clova:
  url: clova-url
  api-key: api-key
  gateway-key: gateway-key
