spring:
  config:
    activate:
      on-profile: prod

  datasource:
    first:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: validate

logging:
  level:
    com.foodkeeper: info

jwt:
  secret-key: ${JWT_SECRET_KEY}

clova:
  url: ${CLOVA_MODEL_URL}
  api-key: ${CLOVA_API_KEY}
  gateway-key: ${CLOVA_GATEWAY_KEY}