spring:
  config:
    activate:
      on-profile: local
    import: "optional:file:.env[.properties]"


  datasource:
    first:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
      username: sa
      password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    com.foodkeeper: debug

jwt:
  secret-key: testtesttesttesttesttesttesttest

cloud:
  aws:
    s3:
      bucket: food-keeper
    credentials:
      access-key: naver-access-key
      secret-key: naver-secret-key
    region:
      static: kr-standard
    stack:
      auto: false

custom:
  s3:
    endpoint: naver-storage-url

clova:
  url: clova-url
  api-key: api-key

client:
  url: http://localhost:8080
